# #defining the resource PVC, which is nothing but, claiming the required storage from earlier defined PV
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql
#   namespace: expense
# spec:
#   storageClassName: "expense-ebs" # sc name is given
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 4Gi

#head-less service definition
apiVersion: v1
kind: Service
metadata: 
  name: headless-service-mysql
  namespace: expense
spec:
  clusterIP: none #this is called headless service
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 3306   #service port
      targetPort: 3306  #pod port
  ---
apiVersion: v1   #service definition
kind: Service
metadata: 
  name: mysql-service
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 3306   #service port
      targetPort: 3306  #pod port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "headless-service-mysql" #provide head-less service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db # has to match .spec.selector.matchLabels
    spec: 
      containers:
      - name: mysql
        image: nagamanimuvva/mysql:v1.0
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      # nodeSelector:
      #     topology.kubernetes.io/zone: us-east-1c
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
  #pvc declaration, it is mandatory
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi
  ---
  