#defining the resource PVC, which is nothing but, claiming the required storage from earlier defined PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs" # sc name is given
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: nagamanimuvva/mysql:v1.0
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql